name: study_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^2.5.1
  file_picker: ^6.2.0
  firebase_storage: ^11.6.10
  intl: ^0.19.0
  uuid: ^4.3.3
  firebase_messaging: ^14.7.20
  googleapis_auth: ^1.5.1
  awesome_notifications: ^0.9.3+1
  smooth_page_indicator: ^1.1.0
  open_file: ^3.3.2
  dio: ^5.4.2+1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5


# flutter_launcher_icons:
#   # ios: false
#   # image_path: "assets/icon/icon.png"
#   # remove_alpha_ios: true
#   android: true

#   image_path: "assets/icons/icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/

